<?php

namespace Database\Seeders;

use App\Models\CatalogoMunicipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CatMunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CatalogoMunicipio::insert([
            ['id' => 1, 'descripcion' => 'Acambay de Ruíz Castañeda'],
            ['id' => 2, 'descripcion' => 'Acolman'],
            ['id' => 3, 'descripcion' => 'Aculco'],
            ['id' => 4, 'descripcion' => 'Almoloya de Alquisiras'],
            ['id' => 5, 'descripcion' => 'Almoloya de Juárez'],
            ['id' => 6, 'descripcion' => 'Almoloya del Río'],
            ['id' => 7, 'descripcion' => 'Amanalco'],
            ['id' => 8, 'descripcion' => 'Amatepec'],
            ['id' => 9, 'descripcion' => 'Amecameca'],
            ['id' => 10, 'descripcion' => 'Apaxco'],
            ['id' => 11, 'descripcion' => 'Atenco'],
            ['id' => 12, 'descripcion' => 'Atizapán'],
            ['id' => 13, 'descripcion' => 'Atizapán de Zaragoza'],
            ['id' => 14, 'descripcion' => 'Atlacomulco'],
            ['id' => 15, 'descripcion' => 'Atlautla'],
            ['id' => 16, 'descripcion' => 'Axapusco'],
            ['id' => 17, 'descripcion' => 'Ayapango'],
            ['id' => 18, 'descripcion' => 'Calimaya'],
            ['id' => 19, 'descripcion' => 'Capulhuac'],
            ['id' => 20, 'descripcion' => 'Coacalco de Berriozábal'],
            ['id' => 21, 'descripcion' => 'Coatepec Harinas'],
            ['id' => 22, 'descripcion' => 'Cocotitlán'],
            ['id' => 23, 'descripcion' => 'Coyotepec'],
            ['id' => 24, 'descripcion' => 'Cuautitlán'],
            ['id' => 25, 'descripcion' => 'Chalco'],
            ['id' => 26, 'descripcion' => 'Chapa de Mota'],
            ['id' => 27, 'descripcion' => 'Chapultepec'],
            ['id' => 28, 'descripcion' => 'Chiautla'],
            ['id' => 29, 'descripcion' => 'Chicoloapan'],
            ['id' => 30, 'descripcion' => 'Chiconcuac'],
            ['id' => 31, 'descripcion' => 'Chimalhuacán'],
            ['id' => 32, 'descripcion' => 'Donato Guerra'],
            ['id' => 33, 'descripcion' => 'Ecatepec de Morelos'],
            ['id' => 34, 'descripcion' => 'Ecatzingo'],
            ['id' => 35, 'descripcion' => 'Huehuetoca'],
            ['id' => 36, 'descripcion' => 'Hueypoxtla'],
            ['id' => 37, 'descripcion' => 'Huixquilucan'],
            ['id' => 38, 'descripcion' => 'Isidro Fabela'],
            ['id' => 39, 'descripcion' => 'Ixtapaluca'],
            ['id' => 40, 'descripcion' => 'Ixtapan de la Sal'],
            ['id' => 41, 'descripcion' => 'Ixtapan del Oro'],
            ['id' => 42, 'descripcion' => 'Ixtlahuaca'],
            ['id' => 43, 'descripcion' => 'Xalatlaco'],
            ['id' => 44, 'descripcion' => 'Jaltenco'],
            ['id' => 45, 'descripcion' => 'Jilotepec'],
            ['id' => 46, 'descripcion' => 'Jilotzingo'],
            ['id' => 47, 'descripcion' => 'Jiquipilco'],
            ['id' => 48, 'descripcion' => 'Jocotitlán'],
            ['id' => 49, 'descripcion' => 'Joquicingo'],
            ['id' => 50, 'descripcion' => 'Juchitepec'],
            ['id' => 51, 'descripcion' => 'Lerma'],
            ['id' => 52, 'descripcion' => 'Malinalco'],
            ['id' => 53, 'descripcion' => 'Melchor Ocampo'],
            ['id' => 54, 'descripcion' => 'Metepec'],
            ['id' => 55, 'descripcion' => 'Mexicaltzingo'],
            ['id' => 56, 'descripcion' => 'Morelos'],
            ['id' => 57, 'descripcion' => 'Naucalpan de Juárez'],
            ['id' => 58, 'descripcion' => 'Nezahualcóyotl'],
            ['id' => 59, 'descripcion' => 'Nextlalpan'],
            ['id' => 60, 'descripcion' => 'Nicolás Romero'],
            ['id' => 61, 'descripcion' => 'Nopaltepec'],
            ['id' => 62, 'descripcion' => 'Ocoyoacac'],
            ['id' => 63, 'descripcion' => 'Ocuilan'],
            ['id' => 64, 'descripcion' => 'El Oro'],
            ['id' => 65, 'descripcion' => 'Otumba'],
            ['id' => 66, 'descripcion' => 'Otzoloapan'],
            ['id' => 67, 'descripcion' => 'Otzolotepec'],
            ['id' => 68, 'descripcion' => 'Ozumba'],
            ['id' => 69, 'descripcion' => 'Papalotla'],
            ['id' => 70, 'descripcion' => 'La Paz'],
            ['id' => 71, 'descripcion' => 'Polotitlán'],
            ['id' => 72, 'descripcion' => 'Rayón'],
            ['id' => 73, 'descripcion' => 'San Antonio la Isla'],
            ['id' => 74, 'descripcion' => 'San Felipe del Progreso'],
            ['id' => 75, 'descripcion' => 'San Martín de las Pirámides'],
            ['id' => 76, 'descripcion' => 'San Mateo Atenco'],
            ['id' => 77, 'descripcion' => 'San Simón de Guerrero'],
            ['id' => 78, 'descripcion' => 'Santo Tomás'],
            ['id' => 79, 'descripcion' => 'Soyaniquilpan de Juárez'],
            ['id' => 80, 'descripcion' => 'Sultepec'],
            ['id' => 81, 'descripcion' => 'Tecámac'],
            ['id' => 82, 'descripcion' => 'Tejupilco'],
            ['id' => 83, 'descripcion' => 'Temamatla'],
            ['id' => 84, 'descripcion' => 'Temascalapa'],
            ['id' => 85, 'descripcion' => 'Temascalcingo'],
            ['id' => 86, 'descripcion' => 'Temascaltepec'],
            ['id' => 87, 'descripcion' => 'Temoaya'],
            ['id' => 88, 'descripcion' => 'Tenancingo'],
            ['id' => 89, 'descripcion' => 'Tenango del Aire'],
            ['id' => 90, 'descripcion' => 'Tenango del Valle'],
            ['id' => 91, 'descripcion' => 'Teoloyucan'],
            ['id' => 92, 'descripcion' => 'Teotihuacán'],
            ['id' => 93, 'descripcion' => 'Tepetlaoxtoc'],
            ['id' => 94, 'descripcion' => 'Tepetlixpa'],
            ['id' => 95, 'descripcion' => 'Tepotzotlán'],
            ['id' => 96, 'descripcion' => 'Tequixquiac'],
            ['id' => 97, 'descripcion' => 'Texcaltitlán'],
            ['id' => 98, 'descripcion' => 'Texcalyacac'],
            ['id' => 99, 'descripcion' => 'Texcoco'],
            ['id' => 100, 'descripcion' => 'Tezoyuca'],
            ['id' => 101, 'descripcion' => 'Tianguistenco'],
            ['id' => 102, 'descripcion' => 'Timilpan'],
            ['id' => 103, 'descripcion' => 'Tlalmanalco'],
            ['id' => 104, 'descripcion' => 'Tlalnepantla de Baz'],
            ['id' => 105, 'descripcion' => 'Tlatlaya'],
            ['id' => 106, 'descripcion' => 'Toluca'],
            ['id' => 107, 'descripcion' => 'Tonatico'],
            ['id' => 108, 'descripcion' => 'Tultepec'],
            ['id' => 109, 'descripcion' => 'Tultitlán'],
            ['id' => 110, 'descripcion' => 'Valle de Bravo'],
            ['id' => 111, 'descripcion' => 'Villa de Allende'],
            ['id' => 112, 'descripcion' => 'Villa del Carbón'],
            ['id' => 113, 'descripcion' => 'Villa Guerrero'],
            ['id' => 114, 'descripcion' => 'Villa Victoria'],
            ['id' => 115, 'descripcion' => 'Xonacatlán'],
            ['id' => 116, 'descripcion' => 'Zacazonapan'],
            ['id' => 117, 'descripcion' => 'Zacualpan'],
            ['id' => 118, 'descripcion' => 'Zinacantepec'],
            ['id' => 119, 'descripcion' => 'Zumpahuacán'],
            ['id' => 120, 'descripcion' => 'Zumpango'],
            ['id' => 121, 'descripcion' => 'Cuautitlán Izcalli'],
            ['id' => 122, 'descripcion' => 'Valle de Chalco Solidaridad'],
            ['id' => 123, 'descripcion' => 'Luvianos'],
            ['id' => 124, 'descripcion' => 'San José del Rincón'],
            ['id' => 125, 'descripcion' => 'Tonanitla'],
        ]);
    }
}
